export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS';
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const LOAD_USERDETAILS_SUCCESS = 'LOAD_USERDETAILS_SUCCESS';

export const LOAD_INFOBOXES_SUCCESS = 'LOAD_INFOBOXES_SUCCESS';
export const LOAD_MONTHLYREPORT_SUCCESS = 'LOAD_MONTHLYREPORT_SUCCESS';
export const LOAD_VISITORREPORT_SUCCESS = 'LOAD_VISITORREPORT_SUCCESS';
export const LOAD_CHATMSG_SUCCESS = 'LOAD_CHATMSG_SUCCESS';
export const LOAD_LATESTMEMBERS_SUCCESS = 'LOAD_LATESTMEMBERS_SUCCESS';
export const LOAD_REPORTFOR30DAYS_SUCCESS = 'LOAD_REPORTFOR30DAYS_SUCCESS';
export const LOAD_BROWSERUSAGE_SUCCESS = 'LOAD_BROWSERUSAGE_SUCCESS';

export const LOAD_STUDENTSLIST_SUCCESS = 'LOAD_STUDENTSLIST_SUCCESS';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS';
