//Lesson   -   Action Types
export const LOAD_LESSONS_LIST = "LOAD_LESSONS_LIST";
export const LOAD_COURSES_LIST = "LOAD_COURSES_LIST";
export const ADD_LESSON_SUCCESS = "ADD_LESSON_SUCCESS";
export const EDIT_LESSON_SUCCESS = "EDIT_LESSON_SUCCESS";
export const DELETE_LESSON_SUCCESS = "DELETE_LESSON_SUCCESS";
export const CLEAR_ADD_LESSON_VALUES = "CLEAR_ADD_LESSON_VALUES";
export const CREATE_SLIDE_REQUEST_SUCCESS = "CREATE_SLIDE_REQUEST_SUCCESS";
export const SLIDE_SECTION_CREATE_REQUEST_SUCCESS =
  "SLIDE_SECTION_CREATE_REQUEST_SUCCESS";
export const SLIDE_SECTION_UPDATE_REQUEST_SUCCESS =
  "SLIDE_SECTION_UPDATE_REQUEST_SUCCESS";
export const LOAD_SLIDE_SECTION = "LOAD_SLIDE_SECTION";
export const LOAD_LESSON_SUCCESS = "LOAD_LESSON_SUCCESS";
export const LOAD_SLIDES_SUCCESS = "LOAD_SLIDES_SUCCESS";
export const LOAD_LESSONS_LOAD_MORE = "LOAD_LESSONS_LOAD_MORE";
export const LOAD_COURSES_LOAD_MORE = "LOAD_COURSES_LOAD_MORE";
export const CREATE_VIDEO_REQUEST_SUCCESS = "CREATE_VIDEO_REQUEST_SUCCESS";
// export const CREATE_VIDEO_REQUEST_SUCCESS = 'CREATE_VIDEO_REQUEST_SUCCESS';
// export const CREATE_VIDEO_REQUEST_SUCCESS = 'CREATE_VIDEO_REQUEST_SUCCESS';
